app:
  env: "dev"
  name: "ginapi-server"
server:
  host: "127.0.0.1"
  port: "8080"
mysql:
  host: "127.0.0.1"
  port: "3306"
  database: "gin-admin"
  username: "root"
  password: ""
redis:
  host: "127.0.0.1"
  prot: "6379"
jwt:
  secret: "test"
  ttl: "2"